services:
  - type: web
    name: internetrecords
    env: node
    buildCommand: npm install && npm run build && ls -R dist
    startCommand: cd /opt/render/project/src && node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_INITIAL_EMAIL
        sync: false
      - key: ADMIN_INITIAL_PASSWORD
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: music-files
